[package]
name = "oxidie_checkers"
version = "0.1.0"
edition = "2021"
include = ["/src/startState.txt"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"