name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
#   style:
#     name: Check Style
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1

#       - name: Install rust
#         uses: actions-rs/toolchain@v1
#         with:
#           toolchain: stable
#           components: rustfmt
#           profile: minimal
#           override: true

#       - name: cargo fmt -- --check
#         uses: actions-rs/cargo@v1
#         with:
#           command: fmt
#           args: --all -- --check
  deploy:
    name: deploy
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [x86_64-pc-windows-msvc,x86_64-unknown-linux-gnu, aarch64-apple-darwin,x86_64-apple-darwin]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          #strip target/${{ matrix.target }}/release/oxidieCheckers
          cd target/${{ matrix.target }}/release          
          tar czvf ../../../oxidieCheckers-${{ matrix.target }}.tar.gz oxidieCheckers
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        # TODO: if any of the build step fails, the release should be deleted.
        with:
            files: 'oxidieCheckers*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
